### ISSUE TITLE
Server graceful shutdown concerns 

### ISSUE THREAD

**Issue by sergio-bershadsky** [irmen/Pyro5#15] opened 2019-10-22 06:20 UTC
Would be great to have some points in manual, describing ways to shutdown server without interrupting running processes and preventing new calls to start running.

**Comment by irmen** [comment] 2019-10-22 14:26
You can do so by using a suitable loopCondition parameter
https://pyro5.readthedocs.io/en/latest/servercode.html#running-the-request-loop

What additional information would you like to see in the manual?

**Comment by sergio-bershadsky** [comment] 2019-10-22 14:27
Thanks! Looks like it will work for me. Will test it.

**Comment by sergio-bershadsky** [comment] 2019-10-22 14:34
I need a gracefull shutdown on k8s environment. I will test it and return with some comments, thanks!

**Comment by sergio-bershadsky** [comment] 2019-10-22 15:07
Tried to use shutdown method on daemon: 

Here is how I start Pyro5 service:

```python
def run(handler):

    daemon = Daemon(
        host=settings.get("host"),
        port=settings.get("port"),
        nathost=settings.get("public_host"),
        natport=settings.get("public_port"),
    )

    uri = daemon.register(publish(handler))

    ns = locate_ns()
    ns.register(
        f"handler/{handler.name}/{uuid.uuid4()}",
        uri=uri,
        metadata={
            "handler",
            f"name:{handler.name}",
            f"version:{handler.version}",
        }
    )

    # register graceful shutdown
    def exit_gracefully(signum, frame):
        print(f"Shutting down gracefully exit code: {signum}")
        daemon.shutdown()

    signal.signal(signal.SIGINT, exit_gracefully)
    signal.signal(signal.SIGTERM, exit_gracefully)

    print("Ready. Object uri =", uri)
    daemon.requestLoop()
```

Handler is smth like this

```python
    @expose
    def run(self):
        for i in range(60):
            print(i)
            time.sleep(1)
```

Doing SIGINT leads to break run earlier than 60 seconds. The time between SIGINT and actual shutdown is 5 seconds: 

`Pyro5/server.py:326`

```python
    def shutdown(self):
        """Cleanly terminate a daemon that is running in the requestloop."""
        log.debug("daemon shutting down")
        self.streaming_responses = {}
        time.sleep(0.02)
        self.__mustshutdown.set()
        if self.transportServer:
            self.transportServer.shutdown()
            time.sleep(0.02)
        self.close()
        self.__loopstopped.wait(timeout=5)  # use timeout to avoid deadlock situations
```

Expecting that actual shutdown just after the run return it's value

**Comment by sergio-bershadsky** [comment] 2019-10-22 16:28
The only solution I found for now, is to check worker thread pool before shutting down:

with `daemon.transportServer.pool.busy`

Works only with `thread` type transportServer

```python 
    # register graceful shutdown
    def exit_gracefully(signum, frame):
        daemon.transportServer.shutting_down = True
        print(f"Shutting down gracefully exit code: {signum} active threads: {len(daemon.transportServer.pool.busy)}")
        while len(daemon.transportServer.pool.busy):
            time.sleep(1)
        daemon.shutdown()

    signal.signal(signal.SIGINT, exit_gracefully)
    signal.signal(signal.SIGTERM, exit_gracefully)```

**Comment by irmen** [comment] 2019-10-26 02:25
You cannot gracefully abort running threads, so I suppose your solution/workaround is valid and needed in this case. Another solution may be to just exit() the whole server process at shutdown?

**Comment by irmen** [comment] 2019-12-27 14:36
For more/better control of a server shutdown, you can also try the multiplex server instead of the thread based one. It won't have shutdown issues caused by the use of threads.
Closing this issue now, feel free to reopen/add comments if desired

**Closed by irmen** 2019-12-27 14:36 UTC
